name: Build macOS Electron app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run translations
        run: npm run translate

      - name: Build the Electron app (x64 & arm64)
        run: npm run build:nopublish
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
          CSC_IDENTITY_AUTO_DISCOVERY: false
          GH_TOKEN: ""
          ELECTRON_BUILDER_PUBLISH: "never"
          VITE_DISCORD_FEEDBACK_WEBHOOK_URL: ${{ secrets.VITE_DISCORD_FEEDBACK_WEBHOOK_URL }}
          VITE_DISCORD_REPORT_BUG_WEBHOOK_URL: ${{ secrets.VITE_DISCORD_REPORT_BUG_WEBHOOK_URL }}
          VITE_DISCORD_REPORT_CONTENT_WEBHOOK_URL: ${{ secrets.VITE_DISCORD_REPORT_CONTENT_WEBHOOK_URL }}
          VITE_DISCORD_APPLICATIONS_WEBHOOK_URL: ${{ secrets.VITE_DISCORD_APPLICATIONS_WEBHOOK_URL }}
          VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
          VITE_CLIENT_SECRET: ${{ secrets.VITE_CLIENT_SECRET }}

      - name: Create Universal macOS Binary
        run: |
          mkdir -p release/universal
          # Find the specific version directory
          VERSION_DIR=$(find release -type d -name "[0-9]*.[0-9]*.[0-9]*-*" -o -name "[0-9]*.[0-9]*.[0-9]*" | head -1)
          echo "Using version directory: $VERSION_DIR"

          # Copy the arm64 app to the universal directory as a base
          cp -r "$VERSION_DIR/mac-arm64/Fultimator.app" "$VERSION_DIR/universal/Fultimator.app"

          # Create the directory for the universal binary if it doesn't exist
          mkdir -p "$VERSION_DIR/universal/Fultimator.app/Contents/MacOS"

          # Create the universal binary
          lipo -create -output "$VERSION_DIR/universal/Fultimator.app/Contents/MacOS/Fultimator" \
            "$VERSION_DIR/mac/Fultimator.app/Contents/MacOS/Fultimator" \
            "$VERSION_DIR/mac-arm64/Fultimator.app/Contents/MacOS/Fultimator"

      - name: Package Universal DMG
        run: |
          VERSION_DIR=$(find release -type d -name "[0-9]*.[0-9]*.[0-9]*-*" -o -name "[0-9]*.[0-9]*.[0-9]*" | head -1)
          npm exec electron-builder -- --mac --dir "$VERSION_DIR/universal/Fultimator.app" --config.dmg.title="Fultimator Universal" --config.dmg.icon="public/icons/app.icns" --config.dmg.contents=[{"x":448,"y":344,"type":"link","path":"/Applications"},{"x":192,"y":344,"type":"file","path":"$VERSION_DIR/universal/Fultimator.app"}]

      - name: List build directory contents
        run: find release -type f -name "*.dmg" | sort

      - name: Upload macOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: fultimator-macos-${{ github.sha }}
          path: release/**/*.dmg
