name: Build macOS Electron app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run translations
        run: npm run translate

      - name: Build the Electron app (x64 & arm64)
        run: npm run build:nopublish
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
          CSC_IDENTITY_AUTO_DISCOVERY: false
          GH_TOKEN: ""
          ELECTRON_BUILDER_PUBLISH: "never"
          VITE_DISCORD_FEEDBACK_WEBHOOK_URL: ${{ secrets.VITE_DISCORD_FEEDBACK_WEBHOOK_URL }}
          VITE_DISCORD_REPORT_BUG_WEBHOOK_URL: ${{ secrets.VITE_DISCORD_REPORT_BUG_WEBHOOK_URL }}
          VITE_DISCORD_REPORT_CONTENT_WEBHOOK_URL: ${{ secrets.VITE_DISCORD_REPORT_CONTENT_WEBHOOK_URL }}
          VITE_DISCORD_APPLICATIONS_WEBHOOK_URL: ${{ secrets.VITE_DISCORD_APPLICATIONS_WEBHOOK_URL }}
          VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
          VITE_CLIENT_SECRET: ${{ secrets.VITE_CLIENT_SECRET }}

      - name: Create Universal macOS Binary
        run: |
          mkdir -p release/universal
          lipo -create -output release/universal/Fultimator.app/Contents/MacOS/Fultimator \
            release/*-x64/Fultimator.app/Contents/MacOS/Fultimator \
            release/*-arm64/Fultimator.app/Contents/MacOS/Fultimator
          cp -r release/*-arm64/Fultimator.app release/universal/
          mv release/universal/Fultimator.app release/universal/Fultimator-Mac-Universal.app

      - name: Package Universal DMG
        run: |
          npm exec electron-builder -- --mac universal

      - name: List build directory contents
        run: find release -type f -name "*.dmg" | sort

      - name: Upload macOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: fultimator-macos-${{ github.sha }}
          path: release/**/*.dmg
